name: Brewski
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/YuPototo

favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since:
  name: 
  url: 


